Feature/benchmarking
keep-starknet-strange/kaioshin pull request #23
Opened 2023-02-23 11:55 UTC by EvolveArt

Still wip.
A few things missing : 
- [x] CI Workflow
- [ ] Make it more modular and configurable
- [x] Metrics scripts

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: #4 

# What is the new behavior?

- Leverage [artillery](https://github.com/dwellir-public/artillery-engine-substrate) to conduct performance tests.
- Creates a new `benchmarking` folder at the root of the repo.
- Provide a few samples scripts inside `benchmarking/scripts` that can be used to perform load or smoke tests.
- Helper functions are written inside `scripts/functions.js` to interact with the `cairo` pallet through polkadotjs api.

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

- I'm a bit sad it's in javscript, but polkadotjs is the main tool within the substrate ecosystem.
- On the long run we should probably fork the [artillery engine](https://github.com/dwellir-public/artillery-engine-substrate) and add new features there directly instead of bloating this repo.

2023-03-15 08:04 UTC, abdelhamidbakhta commented
what is the status of this PR ?

2023-03-15 19:13 UTC, EvolveArt commented
> what is the status of this PR ?

Waiting for a proper devops setup to be included as benchmarks against gha linux machine is very slow and not worth to be in the CI. 

I've added the instructions to run benchmarks in `./benchmarking/README.md`.
I've also removed the CI so we can merge this PR and add the CI whenever the AWS/Hetzner instances are ready what do you think?

2023-03-16 13:24 UTC, abdelhamidbakhta requested changes

2023-03-16 13:24 UTC, abdelhamidbakhta commented on .github/workflows/check.yml
> +      # - name: Save runtime wasm
please remove commented lines

2023-03-16 14:07 UTC, abdelhamidbakhta approved these changes

2023-03-16 14:07 UTC, merged